### ISSUE TITLE
Strange error message for non-terminating binary segment pattern without length

### ISSUE THREAD

**Issue by schuster** [tonyg/racket-bitsyntax#5]
In bit-string-case, if a segment pattern has the binary type, does not specify a length, and is not the last pattern in the sequence, the error given is "default: unbound identifier in module in: default". I assume this pattern sequence should be an error, but the message is certainly odd.

    #lang racket

    (require bitsyntax)

    (define test #"\21\21\21\21\21\21")

    (bit-string-case test
     ([(x :: binary)
       (y :: bytes 1)]
      #t))

**Comment by tonyg** [comment]
Thanks!
